import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const root = resolve(new URL("..", import.meta.url).pathname);
const sourcePath = resolve(root, "prompts/satire-engine.md");
const targetPath = resolve(root, "apps/worker/src/generated/satire-engine.ts");

const prompt = await readFile(sourcePath, "utf8");
const body = `// Generated by scripts/sync-prompt.mjs. Do not edit directly.\nexport const SATIRE_ENGINE_PROMPT = ${JSON.stringify(prompt)};\n`;

await mkdir(dirname(targetPath), { recursive: true });
await writeFile(targetPath, body, "utf8");
