import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const root = resolve(new URL("..", import.meta.url).pathname);
const satireSourcePath = resolve(root, "prompts/satire-engine.md");
const nonsenseSourcePath = resolve(root, "prompts/nonsense-engine.md");
const marketSourcePath = resolve(root, "prompts/market-nonsense-engine.md");
const seriousSourcePath = resolve(root, "prompts/serious-engine.md");
const targetPath = resolve(root, "apps/worker/src/generated/satire-engine.ts");

const satirePrompt = await readFile(satireSourcePath, "utf8");
const nonsensePrompt = await readFile(nonsenseSourcePath, "utf8");
const marketPrompt = await readFile(marketSourcePath, "utf8");
const seriousPrompt = await readFile(seriousSourcePath, "utf8");
const body = `// Generated by scripts/sync-prompt.mjs. Do not edit directly.
export const SATIRE_ENGINE_PROMPT = ${JSON.stringify(satirePrompt)};
export const NONSENSE_ENGINE_PROMPT = ${JSON.stringify(nonsensePrompt)};
export const MARKET_NONSENSE_ENGINE_PROMPT = ${JSON.stringify(marketPrompt)};
export const SERIOUS_ENGINE_PROMPT = ${JSON.stringify(seriousPrompt)};
`;

await mkdir(dirname(targetPath), { recursive: true });
await writeFile(targetPath, body, "utf8");
